# This is a basic workflow to help you get started with Actions

name: Bazel

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  IMAGE_NAME: counterstrikesource-server
  CR_PAT: ${{ secrets.CR_PAT }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: mishas/setup-bazelisk-action@v1
      - name: Mount bazel cache  # Optional
        uses: actions/cache@v2
        with:
          path: "~/.cache/bazel"
          key: bazel
      - run: bazel build //... //cmd/srcds_exporter:srcds_exporter_image.tar
      - name: Log into registry
        run: echo "$CR_PAT" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - run: |
          docker load --input bazel-bin/cmd/srcds_exporter/srcds_exporter_image.tar
          docker tag bazel/cmd/srcds_exporter:srcds_exporter_image ghcr.io/kleinpa/srcds-exporter:latest
          docker push ghcr.io/kleinpa/srcds-exporter:latest
